<a href="https://colab.research.google.com/github/RewGuardiano/AI_Module_Assignment/blob/main/Iris25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from sklearn.datasets import load_iris


In [8]:
#understand data
iris_data = load_iris()

In [ ]:
print(iris_data['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [9]:
from keras.models import Sequential
from keras.layers import Dense

In [10]:
model = Sequential()
#Adding Layers
model.add(Dense(10, input_dim=4, activation='relu'))
model.add(Dense(5, activation='relu'))
#softmax will get the biggest value
model.add(Dense(3, activation='softmax'))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                      │ (None, 10)                  │              50 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 5)                   │              55 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 3)                   │              18 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 123 (492.00 B)

 Trainable params: 123 (492.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [11]:
X = iris_data['data']
y = iris_data['target']

In [13]:
y.shape

(150,)

In [14]:
X.shape

(150, 4)

In [15]:
from tensorflow.keras.utils import to_categorical

In [16]:
Y_C = to_categorical(y)

In [17]:
model.fit(X, Y_C, epochs=200)

Epoch 1/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3824 - loss: 3.9225
Epoch 2/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3108 - loss: 4.0258 
Epoch 3/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3372 - loss: 3.5531 
Epoch 4/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3255 - loss: 3.1991 
Epoch 5/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3568 - loss: 2.7504 
Epoch 6/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3385 - loss: 2.6178 
Epoch 7/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3459 - loss: 2.2910 
Epoch 8/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3377 - loss: 2.1729 
Epoch 9/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3477 - loss: 1.8242 
Epoch 10/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3498 - loss: 1.5414 
Epoch 11/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3116 - loss: 1.6629 
Epoch 12/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4505 - los

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.
    
    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [19]:
y_train

array([2, 2, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 2, 0, 2, 2, 2, 1, 2, 1, 2, 0,
       1, 2, 1, 0, 0, 1, 0, 2, 0, 2, 1, 1, 0, 2, 1, 2, 1, 2, 2, 0, 2, 2,
       1, 0, 1, 2, 2, 1, 0, 1, 2, 0, 1, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 2,
       0, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 0, 0, 1, 1, 2, 2, 1, 1, 2,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 2, 1, 0, 2, 0, 0,
       2, 1, 1, 1, 1, 2, 1, 1, 1, 2])

In [20]:
Y_pred = model.predict(X_test,)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


In [21]:
Y_pred

array([[9.54426527e-01, 4.55505475e-02, 2.28989593e-05],
       [8.97919238e-01, 1.01874337e-01, 2.06388198e-04],
       [1.84103161e-01, 5.17128170e-01, 2.98768520e-01],
       [7.17304368e-03, 8.92613977e-02, 9.03565526e-01],
       [8.90507698e-01, 1.09241411e-01, 2.50960496e-04],
       [3.54226559e-01, 5.46158969e-01, 9.96145159e-02],
       [6.11846102e-03, 8.01815391e-02, 9.13699985e-01],
       [1.77430008e-02, 1.60243750e-01, 8.22013378e-01],
       [6.08854368e-02, 3.14982384e-01, 6.24132097e-01],
       [1.33861452e-01, 4.58828837e-01, 4.07309741e-01],
       [6.77783648e-03, 8.59172568e-02, 9.07304883e-01],
       [9.31603611e-01, 6.83277622e-02, 6.85926279e-05],
       [8.90695930e-01, 1.09054342e-01, 2.49755598e-04],
       [1.36503726e-02, 1.37073770e-01, 8.49275768e-01],
       [4.50894423e-02, 2.73195267e-01, 6.81715190e-01],
       [3.03596467e-01, 5.45325220e-01, 1.51078314e-01],
       [5.59478113e-03, 7.54718781e-02, 9.18933392e-01],
       [9.20528769e-01, 7.93679

In [22]:
y_test

array([0, 0, 1, 2, 0, 1, 2, 2, 2, 1, 2, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 2, 0])

In [1]:
from tensorflow.keras.utils import to_categorical

In [2]:
y = to_categorical

In [ ]:
#confusion matrix test add here / unseen data

In [24]:
X.shape

(150, 4)

In [25]:
from sklearn import svm #swapping different model
clf = svm.SVC()


In [26]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
clf.fit(X,y)

SVC()

In [28]:
clf.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
clf.score(X,y)

0.9733333333333334